export OutPutDir=/home/afroditi/Dropbox/Apps/Overleaf/GKI_PRD_Final
export InPutDir=/home/afroditi/Dropbox/Apps/Overleaf/General\ Imbalance\ Variables\ for\ Measuring\ Nuclear\ Effects\ and\ Demonstration\ with\ MicroBooNE\ Data/figures/gen/Afro

cp "${InPutDir}"/KineImb.png "${OutPutDir}"/Fig1.png
cp "${InPutDir}"/GKIGraphic.png "${OutPutDir}"/Fig2.png
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_TrueFineBinDeltaPnPlot.pdf "${OutPutDir}"/Fig3.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_TrueFineBinDeltaPTPlot.pdf "${OutPutDir}"/Fig4.pdf
cp "${InPutDir}"/G18RejectionPower.pdf "${OutPutDir}"/Fig5.pdf
cp "${InPutDir}"/G18CutPower.pdf "${OutPutDir}"/Fig6.pdf
cp "${InPutDir}"/ThreeDKI_G18_FSIStudy_TrueFineBinDeltaAlpha3DqPlot.pdf "${OutPutDir}"/Fig7.pdf
cp "${InPutDir}"/ThreeDKI_G18_FSIStudy_TrueFineBinDeltaAlphaTPlot.pdf "${OutPutDir}"/Fig8.pdf
cp "${InPutDir}"/ThreeDKI_GeneratorOverlay_TrueFineBinDeltaAlpha3DqPlot.pdf "${OutPutDir}"/Fig9.pdf
cp "${InPutDir}"/ThreeDKI_GeneratorOverlay_TrueFineBinDeltaAlphaTPlot.pdf "${OutPutDir}"/Fig10.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_TrueFineBinDeltaPhi3DPlot.pdf "${OutPutDir}"/Fig11.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_TrueFineBinDeltaPhiTPlot.pdf "${OutPutDir}"/Fig12.pdf
cp "${InPutDir}"/GeneratorOverlay2D3D_TrueFineBinDeltaAlphaTPlot.pdf "${OutPutDir}"/Fig13.pdf
cp "${InPutDir}"/GeneratorOverlay2D3D_TrueFineBinDeltaPhiTPlot.pdf "${OutPutDir}"/Fig14.pdf
cp "${InPutDir}"/ThreeDKI_GeneratorOverlay_TrueFineBinDeltaPnParPlot.pdf "${OutPutDir}"/Fig15.pdf
cp "${InPutDir}"/ThreeDKI_GeneratorOverlay_TrueFineBinDeltaPnPerpPlot.pdf "${OutPutDir}"/Fig16.pdf
cp "${InPutDir}"/ThreeDKI_GiBUU_InteBreakDown_TrueFineBinDeltaPnParPlot.pdf "${OutPutDir}"/Fig17.pdf
cp "${InPutDir}"/ThreeDKI_GiBUU_no-FSI_InteBreakDown_NoFSITrueFineBinDeltaPnParPlot.pdf "${OutPutDir}"/Fig18.pdf
cp "${InPutDir}"/ThreeDKI_GeneratorOverlay_TrueFineBinDeltaPnPerpxPlot.pdf "${OutPutDir}"/Fig19.pdf
cp "${InPutDir}"/ThreeDKI_GeneratorOverlay_TrueFineBinDeltaPnPerpyPlot.pdf "${OutPutDir}"/Fig20.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_TrueFineBinDeltaPn_DeltaAlpha3Dq_0_00To45_00Plot.pdf "${OutPutDir}"/Fig21.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_TrueFineBinDeltaPn_DeltaAlpha3Dq_135_00To180_00Plot.pdf "${OutPutDir}"/Fig22.pdf
cp "${InPutDir}"/ThreeDKI_G18_FSIStudy_TrueFineBinDeltaPn_DeltaAlpha3Dq_0_00To45_00Plot.pdf "${OutPutDir}"/Fig23.pdf
cp "${InPutDir}"/ThreeDKI_G18_FSIStudy_TrueFineBinDeltaPn_DeltaAlpha3Dq_135_00To180_00Plot.pdf "${OutPutDir}"/Fig24.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_TrueFineBinDeltaAlpha3Dq_DeltaPn_0_00To0_20Plot.pdf "${OutPutDir}"/Fig25.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_TrueFineBinDeltaAlpha3Dq_DeltaPn_0_40To1_00Plot.pdf "${OutPutDir}"/Fig26.pdf
cp "${InPutDir}"/ThreeDKI_G18_FSIStudy_TrueFineBinDeltaAlpha3Dq_DeltaPn_0_00To0_20Plot.pdf "${OutPutDir}"/Fig27.pdf
cp "${InPutDir}"/ThreeDKI_G18_FSIStudy_TrueFineBinDeltaAlpha3Dq_DeltaPn_0_40To1_00Plot.pdf "${OutPutDir}"/Fig28.pdf
cp "${InPutDir}"/GeneXSections_DeltaPnPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig29.pdf
cp "${InPutDir}"/GenieXSections_DeltaPnPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig30.pdf
cp "${InPutDir}"/GeneXSections_DeltaAlpha3DqPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig31.pdf
cp "${InPutDir}"/GenieXSections_DeltaAlpha3DqPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig32.pdf
cp "${InPutDir}"/GeneXSections_DeltaPhi3DPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig33.pdf
cp "${InPutDir}"/GenieXSections_DeltaPhi3DPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig34.pdf
cp "${InPutDir}"/GeneXSections_DeltaPnPerpPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig35.pdf
cp "${InPutDir}"/GenieXSections_DeltaPnPerpPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig36.pdf
cp "${InPutDir}"/GeneXSections_DeltaPnPerpyPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig37.pdf
cp "${InPutDir}"/GenieXSections_DeltaPnPerpyPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig38.pdf
cp "${InPutDir}"/GeneXSections_DeltaPnParPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig39.pdf
cp "${InPutDir}"/GenieXSections_DeltaPnParPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig40.pdf
cp "${InPutDir}"/GeneLogTwoDXSections_SerialDeltaPn_DeltaAlpha3DqPlot_Slice_0_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig41.pdf
cp "${InPutDir}"/GenieLogTwoDXSections_SerialDeltaPn_DeltaAlpha3DqPlot_Slice_0_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig42.pdf
cp "${InPutDir}"/GeneTwoDXSections_SerialDeltaPn_DeltaAlpha3DqPlot_Slice_3_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig43.pdf
cp "${InPutDir}"/GenieTwoDXSections_SerialDeltaPn_DeltaAlpha3DqPlot_Slice_3_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig44.pdf
cp "${InPutDir}"/GeneTwoDXSections_SerialDeltaAlpha3Dq_DeltaPnPlot_Slice_0_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig45.pdf
cp "${InPutDir}"/GenieTwoDXSections_SerialDeltaAlpha3Dq_DeltaPnPlot_Slice_0_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig46.pdf
cp "${InPutDir}"/GeneLogTwoDXSections_SerialDeltaAlpha3Dq_DeltaPnPlot_Slice_2_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig47.pdf
cp "${InPutDir}"/GenieLogTwoDXSections_SerialDeltaAlpha3Dq_DeltaPnPlot_Slice_2_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig48.pdf
cp "${InPutDir}"/GiBUURejectionPower.pdf "${OutPutDir}"/Fig49.pdf
cp "${InPutDir}"/GiBUUCutPower.pdf "${OutPutDir}"/Fig50.pdf
cp "${InPutDir}"/NuWroRejectionPower.pdf "${OutPutDir}"/Fig51.pdf
cp "${InPutDir}"/NuWroCutPower.pdf "${OutPutDir}"/Fig52.pdf
cp "${InPutDir}"/NEUTRejectionPower.pdf "${OutPutDir}"/Fig53.pdf
cp "${InPutDir}"/NEUTCutPower.pdf "${OutPutDir}"/Fig54.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_NoFSITrueFineBinDeltaPnPlot.pdf "${OutPutDir}"/Fig55.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_NoFSITrueFineBinDeltaPTPlot.pdf "${OutPutDir}"/Fig56.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_NoFSITrueFineBinDeltaAlpha3DqPlot.pdf "${OutPutDir}"/Fig57.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_NoFSITrueFineBinDeltaPhi3DPlot.pdf "${OutPutDir}"/Fig58.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_NoFSITrueFineBinDeltaPhiTPlot.pdf "${OutPutDir}"/Fig59.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_NoFSITrueFineBinDeltaPnPerpxPlot.pdf "${OutPutDir}"/Fig60.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_NoFSITrueFineBinDeltaPtxPlot.pdf "${OutPutDir}"/Fig61.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_NoFSITrueFineBinDeltaPnPerpyPlot.pdf "${OutPutDir}"/Fig62.pdf
cp "${InPutDir}"/ThreeDKI_G18_InteBreakDown_NoFSITrueFineBinDeltaPtyPlot.pdf "${OutPutDir}"/Fig63.pdf
cp "${InPutDir}"/GeneXSections_SerialDeltaPn_DeltaAlpha3DqPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig64.pdf
cp "${InPutDir}"/GenieXSections_SerialDeltaPn_DeltaAlpha3DqPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig65.pdf
cp "${InPutDir}"/GeneXSections_SerialDeltaAlpha3Dq_DeltaPnPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig66.pdf
cp "${InPutDir}"/GenieXSections_SerialDeltaAlpha3Dq_DeltaPnPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig67.pdf
cp "${InPutDir}"/GeneXSections_DeltaPnPerpxPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig68.pdf
cp "${InPutDir}"/GenieXSections_DeltaPnPerpxPlot_Combined_v08_00_00_52.pdf "${OutPutDir}"/Fig69.pdf
